package com.myAgeEducation.cbseClass7.maths.LineAndAngle;

public enum AngleQuestionType
{
    IDENTIFY_ANGLE,
    FIND_MEASURE,
    WHICH_IS_ACUTE,
    WHICH_IS_RIGHT,
    WHICH_IS_GREATER,
    SAME_TYPE,
    CLOCK_HAND_TURN,
    POINT_BETWEEN,
    ANGLE_NAME_REVOLUTION,
    CLOCK_FRACTION_REVOLUTION,
    CLOCK_STOP_POINT,
    DIRECTION_REVOLUTION
}
