package com.myAgeEducation.cbseClass7.maths.LineAndAngle;

public enum LineAndAngleQuestionType {
    ANGLE_DEFINITION,
    LINE_DEFINITION,
    POINT_DEFINITION,
    LINE_SEGMENT_DEFINITION,
    RAY_DEFINITION,
    ACUTE_ANGLE_DEFINITION,
    OBTUSE_ANGLE_DEFINITION,
    OBTUSE_RANGE_DEFINITION,
    ACUTE_RANGE_DEFINITION,
    MEASURE_RAY_LINE,
    LINE_SEGMENT_ENDPOINTS,
    OBTUSE_DEGREE_MIN
}
