package com.myAgeEducation.cbseClass7.maths.factors;

public enum FactorQuestionType
{
    LIST_FACTORS,
    FACTOR_TRUE_FALSE,

    GREATEST_FACTOR,

    FACTOR_OF_TWO_NUMBERS,

    FIND_FACTOR,
    FIND_NOT_FACTOR,

    COMMON_FACTOR,
    COMMON_FACTOR_TRUE_FALSE,
    COUNT_COMMON_FACTORS,

    FILL_MISSING_FACTOR,
    PROPERTY_FACTOR_SIZE,
    PROPERTY_FACTORS_FINITE
}
