package com.myAgeEducation.cbseClass7.maths.divisions.facts;

public enum DivisionPictureType {
    PICTURE_IDENTIFY_DIVIDEND,
    PICTURE_IDENTIFY_DIVISOR,
    PICTURE_IDENTIFY_QUOTIENT,
    PICTURE_MISSING_DIVIDEND,
    PICTURE_MISSING_DIVISOR,
    PICTURE_MISSING_QUOTIENT,
    PICTURE_MATCH_EQUATION,
    PICTURE_FIND_MISTAKE,
    PICTURE_COMPLETE_LONG_DIVISION
}
