package com.myAgeEducation.cbseClass7.maths.fractions;

public enum FractionTrueFalseStatementType
{
    NUMERATOR_GREATER_THAN_DENOMINATOR,
    NUMERATOR_LESS_THAN_DENOMINATOR,
    NUMERATOR_EQUAL_TO_DENOMINATOR,

    DENOMINATOR_GREATER_THAN_NUMERATOR,
    DENOMINATOR_LESS_THAN_NUMERATOR,

    NUMERATOR_IS_VALUE,
    DENOMINATOR_IS_VALUE
}